"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { QueryClient, QueryClientProvider } from "react-query";
import { ReactQueryDevtools } from "react-query/devtools";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const queryClient = new QueryClient();
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <div>
            <nav>
              <Link href={"/"}>
                <div className="text-3xl font-bold text-white px-8 py-4">MOVIE</div>
              </Link>
            </nav>
            {children}
            <ReactQueryDevtools initialIsOpen={false} />
          </div>
        </QueryClientProvider>
      </body>
    </html>
  );
}
